name: dokan
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  animate_do: ^3.3.4
  automatic_animated_list: ^1.1.0
  bottom_sheet: ^4.0.4
  country_picker: ^2.0.26
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  custom_navigation_bar: ^0.8.2
  dio: ^4.0.6
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  flutter_cache_manager: ^3.3.2
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.0
  flutter_stepindicator: ^0.1.7
  extended_masked_text: ^3.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  heroicons: ^0.10.0
  intl: ^0.19.0
  iconsax: ^0.0.8
  iconly: ^1.0.1
  #  image_picker: ^1.1.1
  logger: ^2.3.0
  lottie: ^3.1.1
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6
  calendar_date_picker2: ^1.0.2
  time_picker_spinner: ^1.0.0
  flutter_time_picker_spinner: ^2.0.0
  dropdown_button2: ^2.3.9
  rxdart: ^0.27.7
  flutter_colorpicker: ^1.1.0
  simple_gradient_text: ^1.3.0
  image_picker: ^1.1.1

  mime: ^1.0.5
  video_player: ^2.8.6
  path_provider: ^2.0.11
  file_picker: ^8.0.3
  path: ^1.9.0
  flutter_profile_picture: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/login/
    - assets/cover/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-Light.ttf
          weight: 300

    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900